---
title: "MechaCar"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load Library
```{r}
library(dplyr)
```

```{r}
mechacar_df <- read.csv(file="./Resources/MechaCar_mpg.csv",check.names=F,stringsAsFactors = F)
head(mechacar_df)
```

```{r}
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data=mechacar_df))
```

```{r}
suspension_df <- read.csv(file="./Resources/Suspension_Coil.csv",check.names=F,stringsAsFactors = F)
total_summary <- summarize(suspension_df, Mean=mean(PSI),Median=median(PSI),var(PSI), sd(PSI), .groups = 'keep')
```

```{r}
lot_summary <- suspension_df %>% group_by(Manufacturing_Lot) %>% summarize(Mean=mean(PSI),Median=median(PSI),var(PSI), sd(PSI), .groups = 'keep')
```

```{r}
sample_table <- suspension_df %>% sample_n(50) #randomly sample 50 data points
t.test(sample_table$PSI, mu=mean(suspension_df$PSI))
```

```{r}
lot1_df <- subset(suspension_df, Manufacturing_Lot == "Lot1")
t.test(lot1_df$PSI, mu=mean(suspension_df$PSI))
```

```{r}
lot2_df <- subset(suspension_df, Manufacturing_Lot == "Lot2")
t.test(lot2_df$PSI, mu=mean(suspension_df$PSI))
```

```{r}
lot3_df <- subset(suspension_df, Manufacturing_Lot == "Lot3")
t.test(lot3_df$PSI, mu=mean(suspension_df$PSI))
```